name: "Terraform Testing"
 
on:
 pull_request:
   branches:
   - main
 
env:
 TF_LOG: INFO
 
jobs:
 terraform:
   name: "Terraform Module Testing"
   runs-on: ubuntu-latest
   defaults:
     run:
       shell: bash
 
   steps:
     - name: Checkout the repository to the runner
       uses: actions/checkout@v2
 
     - name: Setup Terraform with specified version on the runner
       uses: hashicorp/setup-terraform@v2
       with:
         terraform_version: 1.7.5
    
     - name: Terraform init
       id: init
       run: terraform init
     - name: Terraform test
       id: test
       run: terraform test